version: "3.7"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    network_mode: bridge

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    network_mode: bridge

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
    network_mode: bridge

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    network_mode: bridge

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    network_mode: bridge

volumes:
  db-data:
